// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDmuYkMv5Xt7LYOAMPOznUN7UC9NmNXAgo',
    appId: '1:339429490676:web:480f988f8c09b0b34c83a1',
    messagingSenderId: '339429490676',
    projectId: 'personal-cash-flow-navigator',
    authDomain: 'personal-cash-flow-navigator.firebaseapp.com',
    storageBucket: 'personal-cash-flow-navigator.appspot.com',
    measurementId: 'G-B9HW6PF93W',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDqmjSNrLqIYPcuzp5QoTJNRwgbhUqoRR8',
    appId: '1:339429490676:android:bcef4bada556c4484c83a1',
    messagingSenderId: '339429490676',
    projectId: 'personal-cash-flow-navigator',
    storageBucket: 'personal-cash-flow-navigator.appspot.com',
  );
}
